#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 18 19:09:00 2021

@author: aroona
"""

import pandas as pd

read_file = pd.read_csv (r'Part1.rtf')
read_file.to_csv (r'Energy_Data.csv', index=None)